import type { Metadata } from "next";
import { Geist_Mono, Advent_Pro } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const adventPro = Advent_Pro({
  weight: ["700"], // On charge seulement le poids 700 (Bold)
  subsets: ["latin"],
  variable: "--font-advent-pro", // On crée une variable CSS
  display: "swap", // Meilleure performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adventPro.variable}  font-sans text-[1.5rem] antialiased `}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
